# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('CommentsApp', '0002_auto_20161208_0658'),
        ('GroupsApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='comments',
            field=models.ManyToManyField(to='CommentsApp.Comment'),
        ),
    ]
