# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 04:00
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('CompaniesApp', '0001_initial'),
        ('ProjectsApp', '0002_auto_20161207_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='companyRelationship',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='CompaniesApp.Company'),
        ),
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, verbose_name=b'date created'),
        ),
        migrations.AddField(
            model_name='project',
            name='langs',
            field=models.CharField(default=b'None', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='specialty',
            field=models.CharField(default=b'None', max_length=1000),
        ),
        migrations.AddField(
            model_name='project',
            name='yearsXP',
            field=models.IntegerField(default=b'1', validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
