# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 04:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ProjectsApp', '0003_auto_20161207_0400'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='langs',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='specialty',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='project',
            name='yearsXP',
            field=models.IntegerField(validators=[django.core.validators.MaxValueValidator(10)]),
        ),
    ]
