# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 09:13
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('ProjectsApp', '0006_project_bookmarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bookmarks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='bookmarks',
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='project_name',
            field=models.ManyToManyField(to='ProjectsApp.Project'),
        ),
        migrations.AddField(
            model_name='bookmarks',
            name='user_name',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
