# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-07 05:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0008_professor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='is_engineer',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_professor',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='is_student',
        ),
    ]
