# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 05:24
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('UniversitiesApp', '0004_auto_20161108_1557'),
        ('AuthenticationApp', '0011_merge_20161208_0524'),
    ]

    operations = [
        migrations.AddField(
            model_name='engineer',
            name='almamater',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
        migrations.AddField(
            model_name='myuser',
            name='about',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='contact_info',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='professor',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
        migrations.AddField(
            model_name='student',
            name='languages',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='specialties',
            field=models.CharField(max_length=120, null=True),
        ),
        migrations.AddField(
            model_name='student',
            name='university',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='UniversitiesApp.University'),
        ),
        migrations.AddField(
            model_name='student',
            name='yearsXP',
            field=models.IntegerField(null=True),
        ),
    ]
