# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 09:59
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0012_auto_20161208_0524'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectTwo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=10000)),
                ('langs', models.CharField(max_length=1000)),
                ('yearsXP', models.IntegerField(null=True, validators=[django.core.validators.MaxValueValidator(10)])),
                ('specialty', models.CharField(max_length=1000)),
            ],
        ),
        migrations.AddField(
            model_name='myuser',
            name='bookmarks',
            field=models.ManyToManyField(to='AuthenticationApp.ProjectTwo'),
        ),
    ]
