# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-12-08 11:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('AuthenticationApp', '0013_auto_20161208_0959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='languages',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='specialties',
            field=models.CharField(blank=True, max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='yearsXP',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
